container: "development/dichromat.sif"
is_etam: true
batch: "sample1_debug"

base_change: 'A,G'
secondary_change: 'C,T'
splice_genome: true
depth_site: true

reference:
  contamination:
    - ~/reference/contamination/contamination.fa
    - ref/PET28a-tadA.fa
  genes:
    - ~/reference/genes/Homo_sapiens.rRNA_tRNA_sncRNA.fa
  genome:
    fa: ~/reference/genome/Homo_sapiens/GRCh38.fa
    gtf: ~/reference/genome/Homo_sapiens/GRCh38.release110.gtf
    hisat3n: ~/reference/genome/Homo_sapiens/hisat2_tx_3n/GRCh38.release110

samples:
  sample1:
    data:
      - R1: ~/scratch/debug.fq.gz
    adapter: "GACGTGTGCTCTTCCGATCTNNNNNNNNXXXXXX>XXXAGATCGGAAGAGCGTCGTGT"
    libtype: TAKARAv2
