# Dichromat Production Config Template
samples:
  # Example:
  # sample1:
  #   libtype: "STRANDED"
  #   data:
  #     - R1: "path/to/R1.fq.gz"
  #       R2: "path/to/R2.fq.gz"

reference:
  genome:
    fa: "ref/genome/genome.fa"
    gtf: "ref/genome/genome.gtf"
    hisat3n: "internal_files/ref/genome/index"

# Global Settings
base_change: "C,T"
is_etam: false
markdup: true
container: "development/dichromat.sif"

path:
  hisat3n: "hisat3n"
  samtools: "samtools"
  cutseq: "cutseq"
  markdup: "markdup"
  multiqc: "multiqc"
  python: "python"
