# Pipeline Logic
is_etam: false
skip_samples: []

# Default built-in adapter name (passed to cutseq -A)
libtype: "TAKARAV3"
# Default custom adapter sequence (passed to cutseq -a if libtype is empty)
adapter: ""

path:
  python: "python"
  samtools: "samtools"
  hisat3n: "hisat-3n"
  hisat3nbuild: "hisat-3n-build"
  cutseq: "cutseq"
  falco: "falco"
  bgzip: "bgzip"
  markdup: "markdup"
  variant: "variant"
  multiqc: "multiqc"
  coralsnake: "coralsnake"
  countmut: "countmut"
  # Python scripts (use venv Python with installed packages)
  bam_tag: "/opt/app_venv/bin/python /pipeline/src/bam_tag.py"
  bam_conv: "/opt/app_venv/bin/python /pipeline/src/bam_conv.py"
  merge_samples: "/opt/app_venv/bin/python /pipeline/src/merge_samples.py"
  remap_genome: "/opt/app_venv/bin/python /pipeline/src/remap_genome.py"
  filter_sites: "/opt/app_venv/bin/python /pipeline/src/filter_sites.py"
  sum_groups: "/opt/app_venv/bin/python /pipeline/src/sum_groups.py"
  mqc_mapping: "/opt/app_venv/bin/python /pipeline/src/mqc_mapping.py"
  mqc_sites: "/opt/app_venv/bin/python /pipeline/src/mqc_sites.py"

min_len: 20
markdup: true
splice_genome: true
splice_contamination: false
pileup_ct: false
depth_site: false

# Minimum depth for sites to be included in merged output
# Lower values include more sites but may increase noise
min_merged_depth: 1
